version: '3'
services:
  app: &php
    container_name: app
    image: adrianabo/php:7.4.14-fpm-pcov
    restart: on-failure
    user: www-data
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./docker/php.ini:/usr/local/etc/php/conf.d/docker-php.ini:ro
      - composertmp:/tmp
    environment:
      - "DB_HOST=db"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "DB_PORT=3306"
      - "DB_DATABASE=cfp_election"
      - "DB_USERNAME=cfp_election"
      - "DB_PASSWORD=secret"
      - "COMPOSER_HOME=/tmp"
    depends_on:
      - db
      - redis

  web:
    container_name: cfp_election_web
    image: nginx:1.13-alpine
    working_dir: /var/www/html
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:delegated
      - ./storage/app/public:/var/www/html/public/storage:delegated
    depends_on:
      - app

  db:
    container_name: cfp_election_db
    image: mariadb:10.4
    restart: always
    ports:
      - "33066:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=cfp_election"
      - "MYSQL_USER=cfp_election"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  redis:
    container_name: cfp_election_redis
    image: redis:3.2-alpine
    restart: always
    ports:
      - 36379:6379
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
  composertmp:
